# Generated by Django 5.2.9 on 2025-12-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='category_covers/'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='subcategory_covers/'),
        ),
    ]
